# Generated by Django 3.1.4 on 2022-03-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address1',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address2',
            new_name='street',
        ),
        migrations.AddField(
            model_name='order',
            name='complement',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
