# Generated by Django 3.1.4 on 2022-03-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='post_code',
            new_name='cep',
        ),
    ]
